server.port=30007

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

#spring.datasource.url=jdbc:h2:file:/data/demo
spring.h2.console.enabled=true
spring.application.name=customer-service
spring.sql.init.mode=always

debug=true


logging.level.org.springframework.boot.autoconfigure=ERROR