apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: config-server
    name: config-server
spec:
    replicas: 1
    selector:
        matchLabels:
            app: config-server
    template:
        metadata:
            labels:
                app: config-server
        spec:
            containers:
            - image: rishi154/config-server:0.0.1-SNAPSHOT
              imagePullPolicy: IfNotPresent
              name: config-server
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: api-gateway
    name: api-gateway
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-gateway
    template:
        metadata:
            labels:
                app: api-gateway
        spec:
            containers:
                - image: rishi154/api-gateway:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: api-gateway
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: authentication-service
    name: authentication-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: authentication-service
    template:
        metadata:
            labels:
                app: authentication-service
        spec:
            containers:
                - image: rishi154/authentication-service:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: authentication-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: merchant-service
    name: merchant-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: merchant-service
    template:
        metadata:
            labels:
                app: merchant-service
        spec:
            containers:
                - image: rishi154/merchant:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: merchant-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: product-service
    name: product-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: product-service
    template:
        metadata:
            labels:
                app: product-service
        spec:
            containers:
                - image: rishi154/product:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: product-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: customer-service
    name: customer-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: customer-service
    template:
        metadata:
            labels:
                app: customer-service
        spec:
            containers:
                - image: rishi154/customer:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: customer-service
---

apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: transaction-service
    name: transaction-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: transaction-service
    template:
        metadata:
            labels:
                app: transaction-service
        spec:
            containers:
                - image: rishi154/transaction:0.0.1-SNAPSHOT
                  imagePullPolicy: IfNotPresent
                  name: transaction-service
---


apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: NodePort
  selector:
    app: config-server
  ports:
    - name: http-config
      port: 30005
      targetPort: 30005
      nodePort: 30005

---

apiVersion: v1
kind: Service
metadata:
    name: api-gateway
spec:
    type: LoadBalancer
    selector:
        app: api-gateway
    ports:
        - name: http-apigw
          port: 30008
          targetPort: 8080
          nodePort: 30008
---

apiVersion: v1
kind: Service
metadata:
    name: authentication-service
spec:
    type: NodePort
    selector:
        app: authentication-service
    ports:
        - name: http-authentication
          port: 30006
          targetPort: 30006
          nodePort: 30006

---

apiVersion: v1
kind: Service
metadata:
    name: merchant-service
spec:
    type: NodePort
    selector:
        app: merchant-service
    ports:
        - name: http-merchant
          port: 30009
          targetPort: 30009
          nodePort: 30009

---

apiVersion: v1
kind: Service
metadata:
    name: product-service
spec:
    type: NodePort
    selector:
        app: product-service
    ports:
        - name: http-product
          port: 30010
          targetPort: 30010
          nodePort: 30010

---

apiVersion: v1
kind: Service
metadata:
    name: customer-service
spec:
    type: NodePort
    selector:
        app: customer-service
    ports:
        - name: http-customer
          port: 30007
          targetPort: 30007
          nodePort: 30007

---

apiVersion: v1
kind: Service
metadata:
    name: transaction-service
spec:
    type: NodePort
    selector:
        app: transaction-service
    ports:
        - name: http-transaction
          port: 30011
          targetPort: 30011
          nodePort: 30011
