server.port=30011

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true

spring.application.name=transaction-service

logging.level.com.nvrs.transaction.mapper=INFO
logging.level.org.springframework.beans.factory.support.DefaultListableBeanFactory=ERROR
logging.level.org.springframework.context.event=ERROR
logging.level.org.springframework.boot.autoconfigure=ERROR
logging.level.org.apache.tomcat.util.net.NioEndpoint=ERROR

customer_service_url=http://localhost:30007
merchant_service_url=http://localhost:30009