server.port=30011

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

spring.h2.console.enabled=true
spring.application.name=transaction-service

logging.level.com.nvrs.transaction.mapper=TRACE

logging.level.org.springframework.boot.autoconfigure=ERROR

customer_service_url=http://customer-service:30007
merchant_service_url=http://merchant-service:30009